### PR TITLE
Test/framework graph

### PR DESCRIPTION
**Pull request by letzfets**
Worked on
a)  the connections between sills and dimensions: anchors are moving into the direction, where the connection targets are (instead of static up and down)
b) Trying to arrange the skills in a circle around the dimension

b) is not perfect yet - but I don't know about the original intention of the new design, so I stop it here for now. That was great fun.😎

### CODE REVIEW

**Comment by Greenheart** [comment]
Nice work! This was mostly a random experiment and will likely not get used right now.

Let's look at this after the launch of the IDG survey.

This is still in a separate branch, not yet merged to `main`, so the target branch of this PR should be merging back into the same branch.

**Comment by letzfets** [comment]
> Nice work! This was mostly a random experiment and will likely not get used right now.

It looks like svelte is pretty capable: we can use any svelte component as a building block. And with a modest amount of animations, I can imagine a crazy wild new user experience. ;-)

> 
> Let's look at this after the launch of the IDG survey.

Ahh - ok: I had the impression that this should be up and flying before the IDG summit. 

> 
> This is still in a separate branch, not yet merged to `main`, so the target branch of this PR should be merging back into the same branch.

Ohh - yeah, gotcha! My bad. I've changed the base branch.

**Comment by Greenheart** [comment]
Thanks for the branch swap!

What if we keep this idea for later, but focus on the simpler interactive IDG framework up until the summit? I think the translation infrastructure and engaging the community to create high quality translations for the framework will be more impactful right now. That will give a good value for the community, to inspire further engagement.

This framework for building interactive graphs seems really promising - might be useful in the future :)

**Comment by letzfets** [comment]
> Thanks for the branch swap!

You are welcome.
Is the PR to our playground branch acceptable for now as it is?

> What if we keep this idea for later, but focus on the simpler interactive IDG framework up until the summit? I think the translation infrastructure and engaging the community to create high quality translations for the framework will be more impactful right now. That will give a good value for the community, to inspire further engagement.

Absolutely: I have been dealing quite a lot with Svelte and SvelteKit lately. So I'm finally getting more fluent in this *language* now. But yeah: let's have a look at the decapCMS 3.0 soon. And support the translation work.

> 
> This framework for building interactive graphs seems really promising - might be useful in the future :)

Absolutely: I look forward playing more with that. And I'm feeling pretty comfortable with it, as the principles are pretty much the same as with other graphics tools like TikZ from LaTeX, that I've been using quite a lot before

**Comment by Greenheart** [comment]
That's great that you feel More familiar with Svelte and SvelteKit :)

Yes this is ready to merge!

**Pull request merged**
